version: '3.1'

services:
    db:
        image: mdillon/postgis:11
        restart: always
        expose:
            - 5432

    minio:
        image: minio/minio:latest
        restart: always
        environment:
            - MINIO_ACCESS_KEY=miniominio
            - MINIO_SECRET_KEY=miniominio
        entrypoint: /bin/sh
        command: -c 'mkdir -p /srv/wx-denormalized && minio server /srv'
        expose:
            - 9000

    mongo:
        image: mongo:latest
        restart: always
        expose:
            - 27017

    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - "5775:5775/udp"
            - "5778:5778"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "14268:14268"
            - "16686:16686"
        expose:
            - 6831

    wx_explore:
        image: kallsyms/wx_explore:latest
        restart: always
        depends_on:
            - db
            - minio
            - mongo
            - jaeger
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_HOST=db
            - DATA_PROVIDER=S3
            - INGEST_S3_ACCESS_KEY=miniominio
            - INGEST_S3_SECRET_KEY=miniominio
            - INGEST_S3_REGION=us-east-1
            - INGEST_S3_BUCKET=wx-denormalized
            - INGEST_S3_ENDPOINT=http://minio:9000
            - TRACE_EXPORTER=jaeger
            - JAEGER_HOST=jaeger
        volumes:
            - ./:/opt/wx_explore
        ports:
            - "8080:8080"
