apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wx-explore-api
spec:
  rules:
  - host: cloud.vortexweather.io
    http:
      paths:
      - path: /
        backend:
          serviceName: wx-explore-api
          servicePort: 80
